ktor {

    # Включить режим разработки (Автоперезагрузка работает только в режиме разработки):
    development = true
    development = ${?KTOR_ENV}
    # add in Heroku accaunt: Settings->Config Vars->KTOR_ENV false (https://dashboard.heroku.com/apps/data-website/settings)
    # https://devcenter.heroku.com/articles/config-vars
        # heroku config; heroku config:set GITHUB_USERNAME=joesmith; heroku config:unset GITHUB_USERNAME

    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ ru.alpworking.ApplicationKt.module ]
    }
}
